language: rust
rust:
    - nightly
    - stable
notifications:
    irc: "irc.mozilla.org#piston-internals"
os:
    - linux
    - osx
env:
    global:
        - secure: b65AZCt2SSC/EaI+3T2GS70/Tkym40yf83Ro32Qj5gztKNEVjo/oOJWw6X+HY29V70S4BojhSpnKxv6Z59Uhk/d9ng4lPcjthv5FL1asfhYgIgQa1id3JI1xfkBFAPloLGk/DeSB7G9BZPyVFbfNKimjBf7ViO+odZulq/AGsGI=
script:
    - cargo build -v
    - cargo test -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
